apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld
  namespace: sample
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: sample
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  namespace: sample
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      serviceAccountName: helloworld
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 5000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: helloworld
                version: v2
---
