all:
  hosts:
    master:
      ansible_host: 10.1.1.8
      ip: 10.1.1.8
      access_ip: 10.1.1.8
    node1:
      ansible_host: 10.1.1.9
      ip: 10.1.1.9
      access_ip: 10.1.1.9
    node2:
      ansible_host: 10.1.1.10
      ip: 10.1.1.10
      access_ip: 10.1.1.10
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
