version: '3'
services:
    docker-registry:
        container_name: docker-registry
        image: registry:2
        volumes:
        - "/home/ubuntu/registry:/var/lib/registry"
        ports:
        - "5000:5000"
        restart: always
    docker-registry-ui:
        container_name: docker-registry-ui
        image: parabuzzle/craneoperator:latest
        ports:
        - "8086:80"
        environment:
        - REGISTRY_HOST=registry.aspendemo.org
        - REGISTRY_PORT=5000
        - REGISTRY_PROTOCOL=http
        - SSL_VERIFY=false
        - ALLOW_REGISTRY_LOGIN=false
        restart: always
        depends_on:
        - docker-registry
