aspen-mesh-controlplane:
  # The name of the cluster where Aspen Mesh is being installed.
  clusterId: cluster2

  userAuth:
    # type can be set to `jwt` or `none`. JWT authentication is highly recommended.
    type: none
  
aspen-mesh-secure-ingress:
  # enabled by default, which is highly recommended.
  enabled: true
  # Email to use for Let's Encrypt registration (used for certificate expiry notices)
  # Leave blank ("") if you wish to manage your own TLS certificates.
  lets-encrypt-email: ""
  # Enable external-dns management for Secure Ingress resources
  externalDnsEnabled: false
  
gateways:
  istio-ingressgateway:
    enabled: true
    type: ClusterIP

  istio-egressgateway:
    enabled: true
    env:
      # Needed to route traffic via egress gateway if desired.
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"

prometheus:
  enabled: true

jaeger:
  enabled: true
  
cassandra:
  enabled: true
  fullnameOverride: aspen-mesh-cassandra

external-dns:
  # enabled by default
  enabled: false

global:
  # Provides dns resolution for global services
  podDNSSearchNamespaces:
    - global

  multiCluster:
    enabled: true
    globalDomainSuffix: "global"
    includeEnvoyFilter: true

  controlPlaneSecurityEnabled: true

# Enable istiocoredns for multicluster routing
istiocoredns:
  enabled: true
