--- 
aspen-mesh-controlplane: 
  clusterId: cluster2
  prometheusUrl: "http://aspenmesh:2QxoVJLNG8Rhc7bmYqPmI171@aspen-mesh-metrics-collector.istio-system.svc.cluster2.local:19090"
  userAuth: 
    type: none
aspen-mesh-event-storage: 
  config: 
    cluster_domain: cluster2.local
    cluster_size: 1
    seed_size: 1
  persistence: 
    size: 2Gi
aspen-mesh-metrics-collector: 
  server: 
    persistentVolume: 
      size: 2Gi
aspen-mesh-secure-ingress: 
  enabled: true
  externalDnsEnabled: false
  lets-encrypt-email: ""
external-dns: 
  enabled: false
gateways: 
  istio-egressgateway: 
    autoscaleMax: 3
    autoscaleMin: 1
    enabled: true
    env: 
      ISTIO_META_REQUESTED_NETWORK_VIEW: external
  istio-ingressgateway: 
    autoscaleMax: 3
    autoscaleMin: 1
    enabled: true
    type: ClusterIP
global: 
  controlPlaneSecurityEnabled: true
  multiCluster: 
    enabled: true
    globalDomainSuffix: aspendemo.org
    includeEnvoyFilter: true
  podDNSSearchNamespaces: 
    - aspendemo.org
  proxy: 
    clusterDomain: cluster2.local
  trustDomain: cluster2.local
istiocoredns: 
  enabled: true
jaeger: 
  cassandra: 
    config: 
      cluster_domain: cluster2.local
      cluster_size: 1
      seed_size: 1
    persistence: 
      size: 2Gi
  collector: 
    autoscaling: 
      maxReplicas: 3
      minReplicas: 1
  enabled: true
  ingester: 
    autoscaling: 
      maxReplicas: 3
      minReplicas: 1
prometheus: 
  enabled: true
