--- 
aspen-mesh-controlplane: 
  clusterId: cluster1
  userAuth: 
    type: none
aspen-mesh-event-storage: 
  config: 
    cluster_size: 1
    seed_size: 1
  persistence: 
    size: 2Gi
aspen-mesh-metrics-collector: 
  server: 
    persistentVolume: 
      size: 2Gi
aspen-mesh-secure-ingress: 
  enabled: true
  externalDnsEnabled: false
  lets-encrypt-email: ""
external-dns: 
  enabled: false
gateways: 
  istio-egressgateway: 
    autoscaleMax: 3
    autoscaleMin: 1
    enabled: true
    env: 
      ISTIO_META_REQUESTED_NETWORK_VIEW: external
  istio-ingressgateway: 
    autoscaleMax: 3
    autoscaleMin: 1
    enabled: true
    ports:
    - port: 15021
      targetPort: 15021
      nodePort: 31000
      name: status-port
    - port: 80
      targetPort: 8080
      nodePort: 31001
      name: http2
    - port: 443
      targetPort: 8443
      nodePort: 31002
      name: https
    - port: 15443
      targetPort: 15443
      nodePort: 31003
      name: tls
    type: NodePort
global: 
  meshID: mesh1
  multiCluster:
    enabled: true
    clusterName: cluster1
  network: network1
  meshNetworks:
    network2:
      endpoints:
      - fromRegistry: cluster2
      gateways:
      - address: 10.1.1.8
        port: 15443
istiocoredns: 
  enabled: true
jaeger: 
  cassandra: 
    config: 
      cluster_size: 1
      seed_size: 1
    persistence: 
      size: 2Gi
  collector: 
    autoscaling: 
      maxReplicas: 3
      minReplicas: 1
  enabled: true
  ingester: 
    autoscaling: 
      maxReplicas: 3
      minReplicas: 1
prometheus: 
  enabled: true
