all:
  hosts:
    k8s-1-master:
      ansible_host: 10.1.1.5
      ip: 10.1.1.5
      access_ip: 10.1.1.5
    k8s-1-node1:
      ansible_host: 10.1.1.6
      ip: 10.1.1.6
      access_ip: 10.1.1.6
    k8s-1-node2:
      ansible_host: 10.1.1.7
      ip: 10.1.1.7
      access_ip: 10.1.1.7
    k8s-1-node3:
      ansible_host: 10.1.1.11
      ip: 10.1.1.11
      access_ip: 10.1.1.11
    k8s-1-node4:
      ansible_host: 10.1.1.12
      ip: 10.1.1.12
      access_ip: 10.1.1.12
  children:
    kube-master:
      hosts:
        k8s-1-master:
    kube-node:
      hosts:
        k8s-1-node1:
        k8s-1-node2:
        k8s-1-node3:
        k8s-1-node4:
    etcd:
      hosts:
        k8s-1-master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
