---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      health
      ready
      kubernetes CLUSTER_DOMAIN_LOCAL in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
      }
      hosts /etc/coredns/NodeHosts {
        reload 1s
        fallthrough
      }
      prometheus :9153
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }
    CLUSTER_DOMAIN_GLOBAL:53 {
      errors
      cache 30
      forward . ISTIO_COREDNS_IP:53
    }
  NodeHosts: |
    10.1.1.8 k3s-2-master
    10.1.1.9 k3s-2-node1
    10.1.1.10 k3s-2-node2
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: istiocoredns
    release: istiocoredns
  name: coredns
  namespace: istio-system
data:
  Corefile: |
    .:53 {
      errors
      health
      grpc CLUSTER_DOMAIN_GLOBAL 127.0.0.1:8053
      forward . /etc/resolv.conf {
        except CLUSTER_DOMAIN_GLOBAL
      }
      prometheus :9153
      cache 30
      loop
      reload
    }
